### ISSUE TITLE
add new guidelines: Haufe Lexware API Style Guide

### ISSUE THREAD

**Issue by dret** [arno-di-loreto/apistylebook-web#2]
https://github.com/Haufe-Lexware/api-style-guide might be interesting to add? i am not sure if i am adding this issue on the right repo, there seems to be several that together make up the stylebook. i would be interested to try to add those guidelines myself, if that's something that you think might work.

**Comment by arno-di-loreto** [comment]
The Haufe Lexware styleguide is already on the apistylebook http://apistylebook.com/design/guidelines/haufe-api-styleguide.
Concerning adding new style guide, it would be in this repo https://github.com/arno-di-loreto/apistylebook-data, but I haven't written documentation about that :-) and I think I will refactor the apistylebook to have everything in a single repo (data + builder + web).

**Comment by dret** [comment]
On 2016-12-06 06:34, Arnaud Lauret wrote:
> and I think I will refactor the
> apistylebook to have everything in a single repo (data + builder + web).

that sounds like an excellent idea! ;-)
